# Generated by Django 4.2.20 on 2025-05-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_beer_created_at_alter_beer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='catalog.brewery'),
        ),
    ]
