# Generated by Django 4.2.20 on 2025-05-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_beer_brewery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='catalog.beerstyle'),
        ),
    ]
